language: ruby
rvm:
     - "1.9.3"
     - "2.0.0"
     - "2.1.4"
     - "2.2.1"
script: bundle exec rspec spec
before_install: gem install bundler -v 1.10.6
addons:
    code_climate:
        repo_token: 98eb635c4bb4c62c56e531c05c69d911616f3fa319cf79a86ef7b6b783f42fa9
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - andrew@topdog.za.net
